import { getCollection } from "astro:content";
import type { APIContext } from "astro";

// Minimal RSS 2.0 feed, generated by hand to avoid pulling in
// @astrojs/rss (its install path drops rolldown's optional native
// bindings on this project and breaks the build — known npm quirk).
// Spec: https://www.rssboard.org/rss-specification

function escape(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export async function GET(context: APIContext) {
  // Compose absolute URLs that include the base path. On the staging
  // GH Pages deploy that base is "/piedmontmakers.org/"; on the apex
  // domain cutover it'll just be "/".
  const baseUrl = (
    (context.site?.toString() ?? "https://piedmontmakers.org/") +
    import.meta.env.BASE_URL.replace(/^\//, "")
  ).replace(/\/$/, "");
  const posts = (await getCollection("blog")).sort(
    (a, b) => b.data.pubDate.valueOf() - a.data.pubDate.valueOf()
  );

  const items = posts
    .map((post) => {
      const url = `${baseUrl}/blog/${post.id}`;
      return `    <item>
      <title>${escape(post.data.title)}</title>
      <link>${url}</link>
      <guid isPermaLink="true">${url}</guid>
      <pubDate>${post.data.pubDate.toUTCString()}</pubDate>
      ${post.data.excerpt ? `<description>${escape(post.data.excerpt)}</description>` : ""}
    </item>`;
    })
    .join("\n");

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Piedmont Makers — Blog</title>
    <link>${baseUrl}/blog</link>
    <description>News, project recaps, and updates from Piedmont Makers — a 501(c)(3) supporting STEAM education and maker culture across the East Bay.</description>
    <language>en-us</language>
    <atom:link href="${baseUrl}/rss.xml" rel="self" type="application/rss+xml" />
${items}
  </channel>
</rss>
`;

  return new Response(xml, {
    headers: { "Content-Type": "application/xml; charset=utf-8" },
  });
}
